version: '3'
services:

  rocketride-postgres:
    image: postgres:14.1
    container_name: rocketride-postgres
    env_file:
      - app.env
    networks:
      - rocket-rides
    ports:
      - "5432:5432"

networks:
  rocket-rides:
    name: rocket-rides